---
- name: disable SELINUX
  shell: "{{ item }}"
  with_items:
    - "setenforce 0"
    - "sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config"

- name: modify systemctl config
  shell: "{{ item }}"
  with_items:
    - |
      cat <<EOF | tee /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      EOF
    - sysctl --system
