---
- name: update yum
  shell: "yum -y update"

- name: install yum-plugin
  yum:
    name: "yum-plugin-fastestmirror"
    state: present

- name: register eplrepo GPG-KEY
  shell: "rpm -import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org"

- name: install elrepo repoistory
  yum:
    name: "https://www.elrepo.org/elrepo-release-7.0-4.el7.elrepo.noarch.rpm"
    state: present

- name: install new kernel
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: elrepo-kernel
  with_items:
    - "kernel-ml"
    - "kernel-ml-devel"

- name: set kernel version
  register: latest_kernel_version
  shell: 'grep ^menuentry /boot/grub2/grub.cfg | cut -d "''" -f2 | head -1'

- name: default kernel version
  debug:
    var: latest_kernel_version

- name: Setting Latest Kernel Version
  shell: 'grub2-set-default "{{ latest_kernel_version.stdout }}"'

- name: Reboot System
  reboot:
    reboot_timeout: 3600
