# Ansible Playbook

# - name: Install RKE Handler
#   hosts: rke_handler
#   roles:
#     - andrewrothstein.rke

# - name: Setting RKE NODE
#   hosts:
#     - rke_masters
#     - rke_workers
#   roles:
#     - rke_node

- name: Create RKE User
  hosts: rke_handler
  tasks:
    - ansible.builtin.user:
        name: rke
        password: "rke"
        state: present
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

- name: Shared Key
  hosts:
    - rke_handler
    - rke_masters
    - rke_workers
  become: yes
  become_user: rke
  tasks:
    - name: Debug Kernel Version
      debug:
        var: ansible_host

    - name: ssh-keyscan for known_hosts file
      command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }}
      register: keyscan

    - name: input key
      lineinfile:
        path: ~/.ssh/known_hosts
        line: "{{ item }}"
        create: yes
      with_items:
        - "{{ keyscan.stdout_lines }}"

    # - name: input key for each node
    #   connection: ssh
    #   authorized_key:
    #     user: rke
    #     state: present
    #     key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
