# Ansible Playbook
- name: install master node
  hosts:
    - rke_masters
  roles:
    - rke_master

- name: install worker node
  hosts:
    - rke_workers
  roles:
    - rke_worker

- name: Shared RKE User
  hosts:
    - all
  tasks:
    - include: ./tasks/known_host.yml
    - include: ./tasks/etc_hosts.yml
    - include: ./tasks/shared_rsa_pub.yml

- name: Install RKE
  hosts:
    - rke_worker1
  roles:
    - andrewrothstein.rke

- name: RKE Up
  become: true
  become_user: "{{ rke_user }}"
  hosts:
    - rke_masters
    - rke_workers
  tasks:
    - include: ./tasks/create_rke_user.yml
      when: inventory_hostname == "rke_worker1"
    - include: ./tasks/make_cluster.yml
      when: inventory_hostname == "rke_worker1"
    - include: ./tasks/install_python.yml
      when: inventory_hostname == "rke_worker1"
    - include: ./tasks/rke_up.yml
