# Ansible Playbook
- name: install master node
  gather_facts: false
  hosts:
    - rke_masters
    - rke_workers
  roles:
    - rke_node

- name: Shared RKE User
  gather_facts: true
  hosts:
    - all
  tasks:
    - include: ./tasks/host_requirements.yml

- name: RKE Handler Provisioning
  gather_facts: false
  hosts:
    - rke_master1
roles:
  - andrewrothstein.rke
tasks:
  - include: ./tasks/rke_provisioning.yml

- name: RKE Up
  gather_facts: false
  become: true
  become_user: "{{ rke_user }}"
  hosts:
    - rke_masters
    - rke_workers
  tasks:
    # - include: ./tasks/rke_up.yml
    #   when: inventory_hostname == "rke_master1"
    - include: ./tasks/rke_install_helm.yml
      when: inventory_hostname == "rke_master1"
