---
- name: Install all required dependencies
  yum:
    name:
      - "epel-release"
      - "python3"
      - "python3-devel"
      - "python3-pip"
      - "python-argparse"
    state: present

- name: Install Required Python Library
  shell: "pip3 install pyyaml"
