---
- name: Copy source code
  copy:
    src: "{{ item }}"
    dest: /opt
  with_items:
    - "cluster.yml"
    - "rke_cluster.py"

- name: Make cluster yaml
  run_once: true
  shell: 'python3 /opt/rke_cluster.py --host "{{ hostvars[item][''ansible_facts''][''default_ipv4''][''address''] }}" --role "{{ item }}"'
  loop: "{{ ansible_play_hosts }}"

- name: Move Cluster yaml File
  command: mv /opt/cluster.yml /home/rke
  ignore_errors: true
