---
- name: Install all required dependencies
  yum:
    name:
      - "epel-release"
      - "python3"
      - "python3-devel"
      - "python3-pip"
      - "python-argparse"
      - "python-setuptools"
    state: present

- name: Install Required Python Library
  shell: "pip3 install pyyaml"

- name: Generate an OpenSSH keypair
  become: true
  become_user: "{{ rke_user }}"
  openssh_keypair:
    path: $HOME/{{ rke_user }}/.ssh/id_rsa
    owner: "{{ rke_user }}"
    group: "{{ rke_user }}"
    size: 2048

- name: Get id_rsa.pub From RKE Home directory
  become: true
  become_user: "{{ rke_user }}"
  command: "cat $HOME/{{ rke_user }}/.ssh/id_rsa.pub"
  register: id_pub

- name: Add ansible-node authorized keys
  become: true
  become_user: "{{ rke_user }}"
  lineinfile:
    dest: $HOME/{{ rke_user }}/.ssh/authorized_keys
    line: "{{ id_pub.stdout }}"
