---
- name: Copy source code
  copy:
    src: "{{ item }}"
    dest: "$HOME"
  with_items:
    - "cluster.yml"
    - "rke_cluster.py"

- name: Make cluster yaml
  shell: 'python3 rke_cluster.py --host "{{ hostvars[item][''ansible_facts''][''default_ipv4''][''address''] }}" --role "{{ item }}"'
  loop: "{{ ansible_play_hosts }}"
  args:
    chdir: $HOME

- name: RKE Up
  shell: "/usr/local/bin/rke up --config $HOME/cluster.yml"
  args:
    chdir: $HOME

- name: Create .kube directory authorize
  file:
    path: $HOME/.kube
    state: directory
    mode: "0700"

- name: Create .kube config
  file:
    path: $HOME/.kube/config
    state: touch
    mode: "0600"

- name: Set Default kubeconfig
  shell: "cp $HOME/kube_config_cluster.yml $HOME/.kube/config"

- name: Add a line Kubectl Alias
  ansible.builtin.lineinfile:
    path: $HOME/.bashrc
    line: "{{ item }}"
  with_items:
    - alias k=kubectl
    - complete -F __start_kubectl k

- name: Source Bashrc
  shell: source $HOME/.bashrc
