---
- name: Copy source code
  copy:
    src: "{{ item }}"
    dest: "$HOME/{{ rke_user }}"
  with_items:
    - "cluster.yml"
    - "rke_cluster.py"

- name: Make cluster yaml
  shell: 'python3 rke_cluster.py --host "{{ hostvars[item][''ansible_facts''][''default_ipv4''][''address''] }}" --role "{{ item }}"'
  loop: "{{ ansible_play_hosts }}"
  args:
    chdir: $HOME/{{ rke_user }}

- name: RKE Up
  shell: "/usr/local/bin/rke up --config $HOME/rke/cluster.yml"
  args:
    chdir: /home/{{ rke_user }}

- name: Set Default kubeconfig
  ansible.builtin.copy:
    src: $HOME/kube_config_cluster.yml
    dest: $HOME/.kube/config
