---
- name: disable SELINUX
  shell: "{{ item }}"
  with_items:
    - "setenforce 0"
    - "sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config"

- name: modify systemctl config
  shell: "{{ item }}"
  with_items:
    - |
      cat <<EOF | tee /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      EOF
    - sysctl --system

- name: download kubectl
  shell: "{{ item }}"
  with_items:
    - 'curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"'
    - 'curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"'
    - 'echo "$(<kubectl.sha256) kubectl" | sha256sum --check'
    - "sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl"

- name: alias kubectl
  yum:
    name: bash-completion
    state: present

- name: alias kubectl
  shell: "{{item}}"
  with_items:
    - "source /usr/share/bash-completion/bash_completion"
    - "kubectl completion bash >/etc/bash_completion.d/kubectl"
    - "echo 'source <(kubectl completion bash)' >>~/.bashrc"
    - "echo 'alias k=kubectl' >>~/.bashrc"
    - "echo 'complete -F __start_kubectl k' >>~/.bashrc"
    - "source ~/.bashrc"
