---
- name: ssh server configuration
  shell: "sed -i 's/^#AllowTcpForwarding no$/AllowTcpForwarding yes/' /etc/ssh/sshd_config"

- name: create rke user
  ansible.builtin.user:
    name: rke
    password: "rke"
    groups:
      - docker
    state: present

- name: create ssh directory
  become: yes
  become_user: rke
  file:
    path: $HOME/.ssh
    mode: "0700"
    state: directory

- name: create ssh directory authorize
  become: yes
  become_user: rke
  file:
    path: $HOME/.ssh/authorized_keys
    mode: "0600"
    state: touch
